### PR TITLE
NATS support

### PR DESCRIPTION
**Pull request by ViljarVoidula**
### Summary

Added minimal support for NATS.io as sync backend , test passing  and updated packages from 'npm audit'

### CODE REVIEW

**Comment by daffl** [comment]
Neat, thank you for the pull request @ViljarVoidula! Could you also please add it to the documentation in the Readme? Everything else looks great.

**Comment by ViljarVoidula** [comment]
> Neat, thank you for the pull request @ViljarVoidula! Could you also please add it to the documentation in the Readme? Everything else looks great.

Sure, will finish within this week .

**Comment by ViljarVoidula** [comment]
@daffl sorry for being slow to finish, but updated documentation now

**Comment by daffl** [comment]
Released as v2.2.0, thank you again!

**Pull request merged**
