### PR TITLE
Custom serializer / deserializer support

### PR DESCRIPTION
**Pull request by deskoh**
### Summary

Related issue #128 #87.

* To support custom serializer / deserializer
* Allow configuration of redis client, in particular, to allow receiving of binary data, if using binary serializer like `bson`.

### CODE REVIEW

**Comment by daffl** [comment]
Awesome! This will be really useful. Two small things:

1) Maybe we can add `deserialize` and `serialize` to `app.sync` that is set in each adapter (e.g. https://github.com/feathersjs-ecosystem/feathers-sync/blob/master/lib/adapters/amqp.js#L37). Then it needs to be called only once in https://github.com/feathersjs-ecosystem/feathers-sync/blob/master/lib/core.js#L16 and https://github.com/feathersjs-ecosystem/feathers-sync/blob/master/lib/core.js#L46 so it's always consistent between all adapters.
2) As a test I would just configure the Redis adapter to use the BSON serializer from the documentation so setting serializers is covered.

**Comment by deskoh** [comment]
Do you mean something like the following in https://github.com/feathersjs-ecosystem/feathers-sync/blob/master/lib/core.js?

```js
app.on('sync-in', (rawData) => {
    const { event, path, data, context } = app.sync.deserialize(rawData);
    // ...
})

//...

return app.emit('sync-out', app.sync.serialize({
    event, path, data, context
}));
```

This means `core.test.js` would need a re-write as the default serializer / deserializer is defined when creating the `adapter`.

**Comment by daffl** [comment]
Yes, the core tests would probably need something like

```
app.sync = {
  serialize: data => data,
  deserialize: data => data
}
```

In https://github.com/feathersjs-ecosystem/feathers-sync/blob/master/test/core.test.js#L16

**Comment by deskoh** [comment]
Added BSON serialization tests for date values for `redis` and `AMQP`. Note that `deepStrictEqual` assertion will fail.

**Comment by deskoh** [comment]
@daffl any comments on this PR?

**Comment by daffl** [comment]
This is great, thank you! Released as v1.2.0

**Comment by slajax** [comment]
Excited for 1.2.0!

**Pull request merged**
